version: '3'

volumes:
  employeemanagement_local_postgres_data: {}
  employeemanagement_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
    image: employeemanagement_local_django
    container_name: employeemanagement_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
