apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.app_name}}
  labels:
    app: {{cookiecutter.app_name}}
#  namespace: dapr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.app_name}}
  template:
    metadata:
      labels:
        app: {{cookiecutter.app_name}}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{cookiecutter.app_name}}"
        dapr.io/app-port: "8000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: {{cookiecutter.app_name}}
        image: drf:latest
        env:
        - name: "APP_PORT"
          value: "8000"
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
